name = "Velexi"
uuid = "df234692-c8e6-4477-8353-992663219cfb"
repo = "https://github.com/velexi-research/JuliaRegistry.git"
description = "Velexi Julia Registry"

[packages]
7adf08e9-5ce8-4ef7-b490-37ded1c6a328 = { name = "GeometricAlgebra", path = "G/GeometricAlgebra" }
